apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-share_video-service
  template:
    metadata:
      annotations:
        k8s.aliyun.com/eci-use-specs: ecs.t6-c2m1.large
        k8s.aliyun.com/eci-spot-strategy: "SpotAsPriceGo"
    spec:
      containers:
        - name: video-share_video-service
          image: registry.cn-beijing.aliyuncs.com/b4/video-share_video-service:${DATETIME}-${BUILD_NUMBER}
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
