apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    spec:
      containers:
        - name: video-share_video-service
          image: registry.cn-beijing.aliyuncs.com/b4/video-share_video-service:${DATETIME}-${BUILD_NUMBER}
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
