apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - host: 47.94.196.15
      http:
        paths:
          - path: /
            backend:
              serviceName: svc-api-gateway
              servicePort: 5018
    - host: 47.94.196.15
      http:
        paths:
          - path: /
            backend:
              serviceName: video-service
              servicePort: 80